import { MOVIE_LIST } from "../utils/movies";
import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Alert from "@mui/material/Alert";
import Button from "@mui/material/Button";
import Container from "@mui/material/Container";
import Grid from "@mui/material/Grid";
import TextField from "@mui/material/TextField";
import Typography from "@mui/material/Typography";

import List from "@mui/material/List";
import ListItem from "@mui/material/ListItem";
import ListItemText from "@mui/material/ListItemText";
import SimpleListItem from "../components/SimpleListItem";

export default function Home() {
  const [search, setSearch] = useState("");
  const [year, setYear] = useState("");
  const [errorMessage, setErrorMessage] = useState("");
  const [movies, setMovies] = useState(MOVIE_LIST);

  const handleSubmit = (event) => {
    event.preventDefault();
    // validate the inputs
    validate();
    // filter the movies
    if (errorMessage === "") {
      filterMovies();
    }
  };
  const filterMovies = () => {
    // create a copy of the array
    let searchMovies = [...MOVIE_LIST];

    // use filter to filter through the items
    // Only if there are values in the search or year
    if (search.trim() !== "") {
      searchMovies = searchMovies.filter((movie) => {
        return movie.name.toLowerCase().includes(search.toLowerCase());
      });
    }
    if (year.trim() !== "") {
      searchMovies = searchMovies.filter((movie) => {
        return movie.year === parseInt(year);
      });
    }
    // then we are going to set the state
    setMovies(searchMovies);
  };
  const isNumber = (value) => {
    return !isNaN(value);
  };
  const validate = () => {
    // if the inputs are empty its fine
    if (year.trim() === "") {
      setErrorMessage("");
      return;
    }
    // going to check that the year is a number and that
    // it is 4 digits
    if (!isNumber(year) || year.trim().length !== 4) {
      setErrorMessage(`${year} is not a valid year.`);
      return;
    }
    // at the end if this executes
    setErrorMessage("");
  };
  return (
    <div>
      <Head>
        <title>Our Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>

      <main>
        <Container>
          <Typography
            variant="h2"
            component="h2"
            style={{ textAlign: "center" }}
          >
            Movies
          </Typography>
          <form style={{ width: "100%" }} onSubmit={handleSubmit}>
            <Grid container spacing={2}>
              <Grid item xs={6}>
                <TextField
                  id="search-field"
                  label="search..."
                  variant="standard"
                  sx={{ width: "100%" }}
                  onChange={(e) => {
                    setSearch(e.target.value);
                  }}
                  value={search}
                />
              </Grid>
              <Grid item xs={4}>
                <TextField
                  id="year-field"
                  label="year"
                  variant="standard"
                  onChange={(e) => {
                    setYear(e.target.value);
                  }}
                  value={year}
                  sx={{ width: "100%" }}
                />
              </Grid>
              <Grid item xs={2}>
                <Button type="submit" variant="contained">
                  Filter
                </Button>
              </Grid>
              <Grid item xs={10}>
                {errorMessage !== "" && (
                  <Alert severity="error">{errorMessage}</Alert>
                )}
              </Grid>
            </Grid>
          </form>
          <List sx={{ width: `100%` }}>
            {movies.length === 0 ? (
              <SimpleListItem text={"There are no results, please try again"} />
            ) : (
              <SimpleListItem text={`Found ${movies.length} result(s)`} />
            )}
            {movies.map((movieData, index) => {
              return (
                <SimpleListItem
                  key={index}
                  text={`${movieData.name} (${movieData.year})`}
                />
              );
            })}
          </List>
        </Container>
      </main>
    </div>
  );
}
