import { useState, useEffect } from "react";
import Head from "next/head";

import Typography from "@mui/material/Typography";
import Container from "@mui/material/Container";
import Box from "@mui/material/Box";

import AgencyCard from "@components/AgencyCard";
import NavBar from "@components/NavBar";
import { getAgencies } from "@utils/api/agencies";

export default function Home() {
  // Create a variable of state
  const [agencyDetails, setAgencyDetails] = useState();
  // WHen the component mounts we are going
  useEffect(() => {
    loadAgencies();
  }, []);
  // to load the data (get from backend and setting state)
  const loadAgencies = async () => {
    // get from backend
    const data = await getAgencies();
    // get from front end
    setAgencyDetails(data);
    console.log(data);
  };
  // Loop through the data

  // if agencies is undefined it means it has not yet loaded
  // we are then going to return early
  if (!agencyDetails) {
    return <div>Loading...</div>;
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <Container sx={{ paddingTop: 2 }} component="main" maxWidth="xs">
        <Typography variant="h3">Space Agencies</Typography>
        <Box
          sx={{
            marginTop: 2,
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
          }}
        >
          {agencyDetails.results.map((agency) => {
            return (
              <AgencyCard
                key={agency.id} // just for internal purposes
                id={agency.id}
                imageUrl={agency.image_url}
                name={agency.name}
                abbreviation={agency.abbrev}
                description={agency.description}
              />
            );
          })}
        </Box>
      </Container>
    </div>
  );
}
